### ISSUE TITLE
Different from blink in matrix decomposition of transform function lists equivalent to 'none'.

### ISSUE THREAD

**Issue by rjwright** [web-animations/web-animations-next#179]
This corresponds to chromium bug https://code.google.com/p/chromium/issues/detail?id=412229

Web-animations-next always decomposes keyframe-pairs of transform function lists when they are of different lengths, they contain different functions, or their functions aren't in the same order. However in Blink, if one of the function lists is equivalent to 'none', then matrix decomposition is not performed. E.g. Blink and web-animations-next differ on
```
new Animation(
	elem,
	[{transform: 'rotate(0rad) translate(0px)'},
	{transform: 'translate(800px) rotate(9rad)'}],
	duration);
```
This example makes it easy to see the difference. A decomposed version will perform around a half turn, while a non-decomposed version will perform around 1.5 turns.

**Comment by ewilligers** [comment]
Now fixed in Blink: https://codereview.chromium.org/1170953002
web-animations-next behavior is tested in test/js/matrix-interpolation.js:210
