### ISSUE TITLE
Pausing a player in the same tick doesn't work in chrome.

### ISSUE THREAD

**Issue by cibernox** [web-animations/web-animations-next#267]
Not sure if it's a chrome bug or a bug in the library. Seems suspicious to me that only fails in the only browser that does a fallback to the native implementation.

```js
var animation = new Animation(menu, [{transform: "translate(-320px)"}, {transform: "translate(-320px)"}], 2000);
var player = document.timeline.play(animation);
player.pause();
```

The animation starts anyway.

A bad workaround is to wait until the next tick

```
setTimeout(player.pause, 1);
```

but the first frame of the animation still runs.

Tested in chrome 40.0.2214.69 beta (64-bit) OSX and Chrome for Android 39.
It works in Safari and Firefox. No idea about IE.

**Comment by alancutter** [comment]
Can't seem to repro the bug using Chrome 40. Could you provide the full test case and which Web Animations polyfill target you're using?

**Comment by cibernox** [comment]
I'll do

**Comment by cibernox** [comment]
Ok, I have the failing example, but it happens only with players created from animation groups.

http://jsbin.com/yojinaloca/2/edit?js,output

It fails in chrome, but works in FFox and Safari.

**Comment by rjwright** [comment]
Thanks for the example. I made a copy [on JSBin](http://jsbin.com/famarijaju/1/edit?html,js,console,output) which uses a rawgit import. Also tested locally and observed the same.

**Comment by cibernox** [comment]
I also discovered a workaround to this bug. Setting the currentTime to 0 just after the `pause()` makes this work. In case it gives you a clue.

I've tried to dig into the code but there is little to none documentation at all. It puts the entry barrier to new contributors pretty high.

**Comment by cibernox** [comment]
Another issue I have has to do with the playback rate. I want the move an animation forwards and backwards (that works) but at some point I want to change its speed and reproduce it. It does not work either. 

Example: http://jsbin.com/penese/3/edit

I comment here because I can't be sure that this is bug, but at very least it is very counterintuitive. I am recording an screencast on advanced animations and I finding some unexpected behaviours. 

What is the best channel to have a small chat with someone that can give me some insights on this polyfill? IRC?

**Comment by dstockwell** [comment]
> Another issue I have has to do with the playback rate. I want the move an animation forwards and backwards (that works) but at some point I want to change its speed and reproduce it. It does not work either.
> 
> Example: http://jsbin.com/penese/3/edit
> 
> I comment here because I can't be sure that this is bug, but at very least it is very counterintuitive.

Bug. It appears to me that `playbackRate` is not mutable in web-animations-next.

> What is the best channel to have a small chat with someone that can give me some insights on this polyfill? IRC?

IRC is fine, I'll start #web-animations on freenode.

**Comment by rjwright** [comment]
I have tracked down the cause for this bug and I'm working on a fix now. The fix is quite simple and should be up soon.

**Comment by rjwright** [comment]
https://github.com/web-animations/web-animations-next/pull/274 should rectify this issue
