### ISSUE TITLE
Set the playbackRate on a AnimationGroup's player doesn't work

### ISSUE THREAD

**Issue by cibernox** [web-animations/web-animations-next#268]
Extracted of another issue into its own. 

>Another issue I have has to do with the playback rate. I want the move an animation forwards and backwards (that works) but at some point I want to change its speed and reproduce it. It does not work either.

>Example: http://jsbin.com/yigafe/1/edit

>I comment here because I can't be sure that this is bug, but at very least it is very counterintuitive.

It happens on AnimationsGroups. Not tested in AnimationSequences

**Comment by cibernox** [comment]
I can't guarantee any result, but this bug is really blocking me on a person project, so I'll try to fix it.

Apparently I only have to define a `playbackRate=` setter in the player that goes recursively calling itself on all its children players (if any), and sets the playbackRate when it is a leaf node. Am I right?

**Comment by shans** [comment]
Just recursively setting on child players should be enough. Leaf nodes are actually underlying (web-animations-1) players, so they should respond correctly automatically.

**Comment by cibernox** [comment]
I had to manually set the playbackRate in leaf nodes to make it work, but for some reason when I increase the playback rate the animation "jumps" to the future. No idea why.

See commit https://github.com/cibernox/web-animations-next/commit/f4f5aa5d6136d3e2c2207fece58fcee46e6cb3b8

**Comment by dstockwell** [comment]
> I had to manually set the playbackRate in leaf nodes to make it work, but for some reason when I increase the playback rate the animation "jumps" to the future. No idea why.
> 
> See commit cibernox@f4f5aa5

Instead of:

    this._player._playbackRate = value

I think you want:

    this._player.playbackRate = value

**Comment by dstockwell** [comment]
The group check isn't needed, and you should always set the rate on the group player:

    this._player.playbackRate = value;
    this._forEachChild(function(child) {
      child._player.playbackRate = value;
    });

**Comment by cibernox** [comment]
closed via #269
