### ISSUE TITLE
Cancel the player of an animation group in the same tick does not cancel the animation.

### ISSUE THREAD

**Issue by cibernox** [web-animations/web-animations-next#276]
Similar to #267, but this seems to fail in all browsers.

JSBin proving the bug, and with some commented code proving that one by one it should work:

http://jsbin.com/lovifa/3/edit

**Comment by rjwright** [comment]
Thank you for reporting. I am looking into this now.

It is happening because animation-constructor:awaitStartTime calls updatePendingGroups (which calls _updateChildren) inside a RAF, but cancel is applied immediately. Thus we cancel then we update children.
