### ISSUE TITLE
How to enable off-main-thread animations?

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#300]
Readme says web-animations suppports off-main-thread animations, but from the source code it seems web-animations uses raf, which live in the main thread if I'm not wrong.

Maybe I missed something, but how to enable off-main-thread animations?

**Comment by dstockwell** [comment]
The Polyfill will fall back to a native implementation of Web Animations, including off-main-thread, when available. Right now that's the behavior in Chrome.
