### ISSUE TITLE
source.timing doesn't exist in webAnimations1

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#301]
From https://github.com/web-animations/web-animations-next/blob/c65371f58c53181955ce7d93091f3c9faa8e1e71/src/tick.js#L59

It tries to access `source.timing`, which is always `undefined`, because `scope.Animation` never sets this property, if I'm not wrong.

**Comment by dstockwell** [comment]
Yes, it's not implemented yet, it will be. It's the "Modifiable animation timing" entry in the Build Target Comparison: https://github.com/web-animations/web-animations-next

**Comment by dstockwell** [comment]
See: https://github.com/web-animations/web-animations-next/issues/232
