### ISSUE TITLE
sequence with infinite child does not run infinitely

### ISSUE THREAD

**Issue by samthor** [web-animations/web-animations-next#303]
If you have two animations within a sequence-

A: { duration: 1000 }
B: { duration: 1000, iterations: Infinity }

In the legacy polyfill, this worked as expected: A played, then B played ad infinitum. However in -next, it plays A and then B, and nothing else.

**Comment by shans** [comment]
Can't reproduce on head.

**Comment by samthor** [comment]
For some context: in chatting with @rjwright, we decided this was an interaction with the polyfill and Chrome. As of Chrome 42, this was also fixed for me.
