### ISSUE TITLE
calling getComputedStyle after beginning an animation causes the animation to finish immediately

### ISSUE THREAD

**Issue by akdjr** [web-animations/web-animations-next#321]
Hi!

So I'm not entirely sure if this is a bug, or if I'm just missing something in the way the Web Animations API is intended to work.  Given that additive animations (and thus, single keyframe animations intended to animate an element from it's current state) are not supported yet, we have to call getComputedStyle to generate the first keyframe.

As long as getComputedStyle is called BEFORE calling element.animate, everything appears to work fine.  However, the moment you call getComputedStyle after starting an animation, any and all animations that were started before that call immediately stop and finish.  This is especially noticeable if you are attempting to animate multiple elements at once.

Obviously, the solution is to then make sure to batch up the getComputedStyle calls and perform them before any animates (which is the better way to do it anyway), but is there a reason why this occurs?  This behavior is only present on IE11 and the latest version of Firefox.  On Chrome, it works as expected.

Here is a sample Plunker: http://plnkr.co/Fz2nr6i6VvoyTI7Q9wmj
There are 6 elements, each one animated individually.
animateAll1(): calls getComputedStyle, then animate, and repeats the pattern.  Expected behavior is that all 6 elements animate simultaneously.
animateAll2(): calls getComputed Style 6 times for each element, then animates all 6 elements.  Expected behavior is that all 6 elements animate simultaneously.

On Chrome 41.0.2272.118: All 6 elements animate simultaneously no matter the method.
On Firefox 37.0.1 and IE 11: animateAll1 - only element 6 (the last animate that was called) animates, the other 5 do not.  aniamteAll2 - all 6 animate as expected.

**Comment by dstockwell** [comment]
I don't have time to look in detail at the moment, but just wanted to respond to:

> Obviously, the solution is to then make sure to batch up the getComputedStyle calls and perform them before any animates (which is the better way to do it anyway), but is there a reason why this occurs? This behavior is only present on IE11 and the latest version of Firefox. On Chrome, it works as expected.

There should be no reason this occurs, it does very much seem like a bug in the polyfill -- calling `getComputedStyle` should not cause any state change. In Chrome you're likely falling back to the underlying native implementation.

**Comment by akdjr** [comment]
Good to know!  I figured it was a bug (and that Chrome was obviously using the native implementation), but just wanted to double check, as to not make a fraudulent report.

**Comment by shans** [comment]
Can reproduce this issue using the forced minifill - this is a problem with our polyfill of level 1, not with firefox support.

**Comment by shans** [comment]
Also interesting - this bug doesn't occur if you run the code immediately after load.

**Comment by shans** [comment]
Our getComputedStyle hook is associating a long-out-of-date start time to all pending animations. This is the source of the bug - I'll look into a fix now.

**Comment by ewilligers** [comment]
This bug no longer occurs.
