### ISSUE TITLE
Finish events fired a bit late in gecko?

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#336]
See the test case here http://jsbin.com/tisocikoye/1/edit?html,js,console,output

The background will flash in gecko (stable firefix 37.0.2).

Fine in webkit (safari 8.0.6), blink, trident (ie11).

Not sure what might be cause. Maybe have something to do with the last RAF call and finish event being in different event loop?

**Comment by shans** [comment]
Events are asynchronous and not intended to be used for effect chaining. The FOUC in this case is completely acceptable and may well vary per implementation (or even based on background conditions).

For example, composited animations (transform or opacity) will almost certainly behave the same way on Chrome, especially if there is main-thread contention.

Please note that as animation values override style values, you could achieve the desired effect by adding the out class when you trigger the animation. This will eliminate the FOUC in all cases and has the advantage of being strictly simpler.

**Comment by hgl** [comment]
Thanks for the explanation.

I want to remove animation style after it finishes, so end up nesting a custom effect inside SequenceEffect to chain the effect, seems to be working.

**Comment by alancutter** [comment]
Animations are fill: 'none' by default meaning their styling does not apply after the animation has finished.
As @shans suggested you can just set the final style class at the same time as the animation starts: http://jsbin.com/lujuzexeki/2/edit

**Comment by hgl** [comment]
I don't want animation styles to exist after animation has finished, because I might manipulate it's css styles later.

But thank you for the taking the time to write the demo for me. Really appreciate it.

I currently nest both the animation's effect and a custom effect inside a sequence effect, and add the class in the custom effect. Works like a charm. :)

**Comment by shans** [comment]
I'm glad you've found something that works for you - but I feel compelled to point out that Alan's demo does not actually have any animation styles that exist after the animation has finished. He sets a standard CSS class on the animating element.

**Comment by hgl** [comment]
Oh, oh, oh, right. I was blinded by my own use case.

Yes, in the demo's case, changing the class name upfront is the better way to do it.

My own use case involves moving an element from outside of the viewport to its position in a normal flow. So I add a class before the animation starts to absolutely position it and after the animation has finished I remove the class to place it into normal flow. The class has to be modified after the animation has down without causing FOUC.

So thank you for it pointing out for me @shans, and sorry I didn't look at your code more closely @alancutter. :)

**Comment by dstockwell** [comment]
> My own use case involves moving an element from outside of the viewport to its position in a normal flow. So I add a class before the animation starts to absolutely position it and after the animation has finished I remove the class to place it into normal flow. The class has to be modified after the animation has finished without causing FOUC.

This seems like a case where you want your animation to fill until you are ready to remove the class. I think you could just set fill: 'forwards', then use the finish event to both cancel the animation and remove the css class.

**Comment by hgl** [comment]
Oh, man, I didn't realize canceling an animation would also cancel the fill mode. Thanks for the great tip.

But the even greater picture is that this flow changing animation is part of a sequence. Imagine multiple element doing this kind of animations one after another. I guess you have to use a custom effect to add the class, then the effect, and finally another custom effect to remove the class, and repeat this for other elements?

**Comment by shans** [comment]
If you fill everything backwards and apply position: absolute as one of your animated properties, then as each animation in the sequence completes it will stop applying and transparently pop back into flow. You can then cancel the rule that applies position: absolute to the elements at the same time as you start the animation.

Something like this:

```
<style>
.beforeEntry {
  position: absolute;
  ...
}
</style>
<script>
document.timeline.play(new SequenceEffect([
  new KeyframeEffect(a, [{position: 'absolute'; transform: ...}, {position: 'absolute'; transform: ...}, 
      {duration: 1000, fill: 'backwards'}),
  new KeyframeEffect(b, [{position: 'absolute'; transform: ...}, {position: 'absolute'; transform: ...}, 
      {duration: 1000, fill: 'backwards'}),
  new KeyframeEffect(c, [{position: 'absolute'; transform: ...}, {position: 'absolute'; transform: ...}, 
      {duration: 1000, fill: 'backwards'}),
]));
a.classList.toggle('beforeEntry');
b.classList.toggle('beforeEntry');
c.classList.toggle('beforeEntry');
</script>
```

**Comment by hgl** [comment]
This is getting better and better. Thank you so much.

Just one more question: when you absolutely position an element, it usually requires a couple extra properties to place it correctly. For example, in my case, these are the properties required:

```
position: absolute;
left: 100%;
top: 0;
height: 100px; // when in flow, element has a height of 100%, and its container is 100px tall
```
This mean I have to repeat these properties with the same values for each frame. Should I create a helper function to keep this DRY or is there more elegant way of doing this?

**Comment by alancutter** [comment]
One advantage of this being a Javascript API over CSS @keyframes rules is you have the flexibility to create helper functions to stay DRY. :)

**Comment by hgl** [comment]
I end up inventing something like this:

```js
new UIEffect(target, constProps, keyframes, timing);
```
Where `constProps` contains things like `{position: "absolute"}`.

However, while experimenting with this, I discovered a bug in the native implementation, if all frames contain `display: block`, it doesn't override `display: none` specified in css. Polyfill code doesn't have this issue. See the test case here http://jsbin.com/cojuluziwe/1/edit?html,js,output

Should I report this to crbugs?

**Comment by hgl** [comment]
If I'm not wrong, the spec actually allows you to do

```js
new KeyframeEffect(a, [{position: 'absolute', transform: ...}, {transform: ...}, 1000);
```

and the result is the same as `position: 'absolute'` being specified in the second keyframe? It's just that the native implementation and polyfill currently don't support this?

**Comment by hgl** [comment]
After experimenting with Shane's solution some more, I fell back to custom effects.

Don't get me wrong, I think Shane's solution is great. But in my case I need to deal with css prefixes, although it's dying,  to achieve broader browser support.

Using web animations to add back removed properties means I lose the benefit of a css prefix tool like autoprefixer. Some properties require multiple properties to be generated in order to be prefixed (e.g., `display: flex`). Add all of them with web animations seems pretty cumbersome.

I wonder why you guys want to avoid custom effects? Is it because they are currently unstable?
