### ISSUE TITLE
Custom effect might be delayed if the main thread is busy

### ISSUE THREAD

**Issue by hgl** [web-animations/web-animations-next#337]
Open http://jsbin.com/jubomerahe/1/edit in chrome, the box will shift very quickly to the left when starting to slide to the right, after it has slid down.

Removing the setTimeout code fixes the problem.

The shift is caused by the fact that the custom effect's next sibling's first frame is rendered before the custom effect is played.

Not using native animation also seems to fix the problem.

Not sure it's a problem in the native code or the effect polyfill doesn't play nice with the native code.

**Comment by hgl** [comment]
I seems to have accidentally changed the test case and now it breaks, please wait until it's fixed.

**Comment by shans** [comment]
Yes. This is unfortunately unavoidable, even in the native implementation.

**Comment by hgl** [comment]
> even in the native implementation

Do you mean it's unavoidable only if native animation is implemented but not native custom effect? After reading the source, I guess it's because of the execution order of raf and native animation sampling?

Will this still be the case if both native animation and native custom effect are implemented?

**Comment by shans** [comment]
Absolutely. Fundamentally, the main thread is just that - a single thread. Custom effects (whether polyfilled or native) are serviced on the thread, so if it is busy, they'll be delayed.

**Comment by hgl** [comment]
Thanks for the explanation.

Now I start to realize toggling classes in custom effects might not be a good idea after all.

**Comment by hgl** [comment]
But with that said. Couldn't the compositor thread wait for the main thread to finish before it renders the first frame of the next sibling effect?

Or the rendering order of custom effects and keyframe effects in the same sampling loop is undefined?

**Comment by shans** [comment]
No, that destroys cross-animation timing guarantees.

**Comment by hgl** [comment]
What's cross-animation timing guarantees?

**Comment by shans** [comment]
All animations run on a global timeline, and are anchored by a start time. Animations need to 'line up' on this timeline - whether they're related by groups or not. The timeline can't change just because the main thread becomes busy.

**Comment by hgl** [comment]
Ah, that makes sense.

Your description creates this mental model in my mind, and I wonder if it is correct: if a custom effect and a keyframe effect is played in sequence, and the timeline is advanced that the keyframe effect starts to play, but the main thread is busy, so the custom effect hasn't done, the compositor thread renders the keyframe effect at each sampling, but it doesn't care if main thread is busy or not. So from that point on, the animation is overall smooth but is spread with some glitches rendered by the delayed custom effect?

**Comment by shans** [comment]
That's correct, yup.

One refinement: the rendered output of the custom effect will arrive at the same time as any other main thread animations - all main thread actions will always be in sync.

These might be a frame or two behind any compositor animations, but never in front, and as long as the main thread doesn't jank then everything is synchronized.

So you can choose guaranteed smoothness (compositor animations only), richness (main thread animations + custom effects), or a hybrid that looks correct as long as you keep your main thread actions slim.

**Comment by hgl** [comment]
I think I have a better understanding of how web-animations work now. Thank you very much. :)

Just a quick question, by "doesn't jank", do you mean the main thread finishes before the next sampling happens?

**Comment by shans** [comment]
I think this is probably browser specific. In Chrome, it means the main thread finishes before the commit deadline is exceeded.

**Comment by alancutter** [comment]
If it helps here's a demo of main thread vs compositor thread animations and how jank affects them: http://jsfiddle.net/0c1nm29n/

**Comment by hgl** [comment]
@alancutter

Thanks for the demo. Very succinctly and clearly demonstrated jank, and I realized even if I animate margin left with web animations, it happens on the main thread.

I actually heard the term jank before on google io videos. I know it means animations fall out of 60/30 fps threshold, but was looking for a more precise definition. But I guess this knowledge won't be that important? Probably the techniques to identify the jank frame and optimize animated properties are more important? (reading helps on chrome dev tools right now :)

@shans

Is "commit deadline" a moment that happens periodically which renders things on the screen? Does it happen some time after each sampling? If it isn't a trivia question, please ignore it, I don't feel like taking more of your time. You already answered a lot of my questions (which I'm very grateful). :)

**Comment by dstockwell** [comment]
> I actually heard the term jank before on google io videos. I know it means animations fall out of 60/30 fps threshold, but was looking for a more precise definition. But I guess this knowledge won't be that important? Probably the techniques to identify the jank frame and optimize animated properties are more important? (reading helps on chrome dev tools right now :)

See http://jankfree.org/

**Comment by hgl** [comment]
@dstockwell, thanks. Just discovered it on the dev tools docs.
