### ISSUE TITLE
finish event should not fire when cancel() is called

### ISSUE THREAD

**Issue by dstockwell** [web-animations/web-animations-next#368]

**Comment by miztroh** [comment]
Any update on this?

**Comment by cdata** [comment]
Bump for news.

**Comment by mgiuffrida** [comment]
This bug seems to have been fixed when using the polyfill in Chrome but not when using the polyfill in Firefox 46.

Also, related issue to polyfill the "cancel" event: web-animations/web-animations-js#57

**Comment by dstockwell** [comment]
Fixed by web-animations/web-animations-next#416
