### ISSUE TITLE
Contribution: Timing input Groups

### ISSUE THREAD

**Issue by nordisk** [web-animations/web-animations-next#401]
Hi guys. How can one contribute to this project? I would like to tackle *Timing input (easings, duration, fillMode, etc.) for groups* but don't know if that is in development and I couldn't find any contribution guidelines.

Thanks

**Comment by shans** [comment]
This is a pretty hard one to start with. We're constrained by the fact that the polyfill needs to emulate the web-animations-1 specification, then build features on top of that.

If you're still interested, maybe we could find an easier bug or feature for you to look at first?
