### ISSUE TITLE
Setting final style at non-fill animation kickoff sometimes causes frame draw

### ISSUE THREAD

**Issue by samthor** [web-animations/web-animations-next#406]
See this demo- https://samthor.github.io/web-animations-issues/setfinalstyle.html
Click in the top, white area to cause a delay (~250ms) and then an animation starts. Sometimes, not always, the final position of the animation is shown for a single frame. Click a few times.

In pseudocode, the way to trigger this is-
```js
var finalValue = 'transform(100px, 100px)';
var player = box.animate([{transform: 'none'}, {transform: finalValue}], 2500);
box.style.transform = finalValue;
```
This is as per the suggestion in [web-animations-js#41](https://github.com/web-animations/web-animations-js/issues/41): the final value should be set initially, not as part of the finish callback.

The issue doesn't affect Chrome (even when the polyfill is forced); it has just appeared on Firefox (Mac, 40.0.3) and Safari 8.0.8 (10600.8.9). Safari is easier to trigger.

**Comment by samthor** [comment]
Note that one fix is actually to do this-
```js
window.requestAnimationFrame(function() {
  box.style.transform = finalValue;
});
```

As discussed with the WA team, this whole issue could be because browsers are incorrectly doing a layout _before_ any scheduled `requestAnimationFrame` calls (which the `.animate` triggers too). So by delaying the final value set, we overcome that.

**Comment by dstockwell** [comment]
http://jsfiddle.net/y21y89dz/

**Comment by alancutter** [comment]
One workaround that we discussed would be to apply animated styles in element.animate() since we can't rely on RAF intercepting the rendered style with the animated style.

**Comment by dstockwell** [comment]
> One workaround that we discussed would be to apply animated styles in element.animate() since we can't rely on RAF intercepting the rendered style with the animated style.

We're going to have to do this (make `invalidateEffects` call `tick` directly), unless there are any better ideas.

**Comment by birtles** [comment]
@samthor What is the issue you're seeing in Firefox?

**Comment by samthor** [comment]
@birtles It's the issue that @dstockwell identified in his jsfiddle link.

**Comment by birtles** [comment]
@samthor I can't tell from that fiddle what the problem is.

**Comment by samthor** [comment]
In 45.0 on Mac, try focusing and unfocusing the window containing the jsfiddle. Do this a few times, and you'll see a flash of red, which should never happen (since rAF should be called before anything is drawn).

In 44.0.2 (the version I had before updating to check if it wasn't fixed), the effect seemed to be more obvious.

**Comment by birtles** [comment]
Why should rAF be called before anything is drawn? It happens at the start of the next frame after painting the first (red) frame.

**Comment by dstockwell** [comment]
@birtles in the processing model (https://html.spec.whatwg.org/multipage/webappapis.html#processing-model-8) there should not be an opportunity to interleave other callbacks between running animation frame callbacks and updating the rendering.

**Comment by birtles** [comment]
Oh, I thought you were talking about the initial flash of red (which is permitted, even expected, per spec). I didn't notice the other flashing until I resize the window.

**Comment by birtles** [comment]
Filed Mozilla bug 1255650 for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1255650
